Pull Statuses
stanfordio/truthbrush pull request #22
Opened 2023-09-02 19:36 UTC by s2t2

Updates `created_after` parameter of the `Api#pull_statuses` function to be a datetime, instead of a date, so we can collect statuses posted later in the same day as some previously collected status. Makes this an optional parameter, so default will pull entire timeline.

We could alternatively consider using an approach based on status identifiers instead of status timestamps (assuming the identifiers are in order of their creation). Implements a new optional `since_id` parameter for this purpose.

Implements automated testing to ensure this functionality works.

2023-09-02 19:42 UTC, s2t2 commented on truthbrush/api.py
> -        id = self.lookup(username)["id"]
choosing a different variable name because `id` is an [existing function](https://docs.python.org/3/library/functions.html#id)

2023-09-02 19:43 UTC, s2t2 commented on truthbrush/cli.py
> +api = Api()
Now Api uses these env vars by default.

2023-10-01 03:02 UTC, milesmcc commented on README.md
> +Development setup (ensure you have [Poetry](https://python-poetry.org/) installed):
@s2t2 made a few small changes to the README here — head's up.

2023-10-01 03:15 UTC, milesmcc requested changes
Thanks for these changes! I pushed a few commits myself to get things working, as we also need to change `cli.py` for these updates to work.

Main comment is about verbose logging; could we use `logger.debug` or something comparable?

Thanks again!

2023-10-01 03:15 UTC, milesmcc commented on truthbrush/api.py
> +                    print(url, params)
For these verbose logs, could we use something other than `print`? I think it's important that `stdout` remains reserved for program output (so that you can always pipe to JSONL, even when verbose mode is enabled). I would like us to use `logger.debug` if possible to keep things consistent.

2023-10-01 03:15 UTC, milesmcc commented on truthbrush/api.py
> +                print("PAGE", page_counter)
See above comment (including for all other `print`-based verbose logs).

2023-10-01 03:15 UTC, milesmcc commented on truthbrush/cli.py
Should we also update the CLI parameter to allow providing a precise timestamp in `--created-after`? It seems that we still only support dates. I am happy to leave this as-is but wanted to flag.

2023-10-01 03:15 UTC, milesmcc commented on truthbrush/api.py
> -        self, username: str, created_after: date, replies: bool
To make this work, we also need to update `cli.py` correspondibly. (Don't worry about doing so; I just did 🙂.) The `truthbrush statuses [--created-after]` command in the CLI was not using named arguments (so `created_after` was not passed correctly) and was also providing a date, rather than a datetime.

2023-10-02 00:37 UTC, s2t2 commented on truthbrush/api.py
> +                    print(url, params)
Sure thing. I will replace all the print statements with `logger.debug`.  

I am not the most familiar with different logging options, so thanks for the suggestion!

2023-10-02 00:46 UTC, s2t2 commented
@milesmcc what tool are you using for linting / formatting? autopep8? 

maybe we can configure the repo with certain formatting config / rules and README commands, as desired

2023-10-02 00:48 UTC, s2t2 commented on README.md
> +black .
oh, I see, here is the formatter. great!

2023-10-02 00:50 UTC, s2t2 commented on truthbrush/api.py
> -        self, username: str, created_after: date, replies: bool
OK, nice. I will leave the CLI review to you, and I will be focusing primarily on the API side.

2023-10-02 00:56 UTC, s2t2 commented on truthbrush/cli.py
For the CLI param, if you would like to keep date param support, perhaps we can support both date and/or datetime looking strings, and if the API function sees a date-looking string is passed, it could convert it to a datetime at beginning of day. Or something like that.

Let me know what you'd like to do.

2023-10-02 01:22 UTC, s2t2 commented on truthbrush/api.py
> +                    print(url, params)
OK, logging is now done 🙌

2023-10-02 04:01 UTC, milesmcc commented on truthbrush/cli.py
Thanks — I ended up making the change already, but forgot to close this comment. We're all set.

2023-10-02 04:02 UTC, milesmcc approved these changes

2023-10-02 04:03 UTC, merged

2023-10-02 04:03 UTC, milesmcc commented
Thanks @s2t2!